on:
  workflow_dispatch:
    inputs:
      environment:
        description: "enter the environment to deploy to"
        required: true
      version_identity:
        description: "Identity: enter image tag"
        required: false
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 10s
